# Generated by Django 4.0.4 on 2022-05-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_password',
            field=models.CharField(default='qwerty123', max_length=20),
        ),
    ]
