# Generated by Django 4.0.4 on 2022-06-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateTimeField(verbose_name='Дата выполнения'),
        ),
    ]
