# Generated by Django 4.0.4 on 2022-06-22 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('chat_tgid', models.IntegerField(verbose_name='Чат id')),
                ('user_tgid', models.IntegerField(verbose_name='Пользователь id')),
                ('verification_code', models.CharField(max_length=10, verbose_name='Проверочный код')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tg_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
