# Generated by Django 4.0.4 on 2022-06-23 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_goalcategory_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0007_tguser_category_alter_tguser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tg_user', to='goals.goalcategory'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tg_category', to=settings.AUTH_USER_MODEL),
        ),
    ]
