# Generated by Django 4.0.4 on 2022-06-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_tguser_category_alter_tguser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='verification_code',
        ),
    ]
